services:
  ree:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "6000-6099:6000-6099/udp"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    env_file: .env
